### ISSUE TITLE
Contouring for unstructured mesh

### ISSUE THREAD

**Issue by FranzThomsen1089** [meteoinfo/wContour_CSharp#2]
Hi

How hard would it be to use the library for contouring based on data in an unstructured mesh ... i.e. xyz data?

Kind Regards 
Franz

**Comment by Yaqiang** [comment]
Only grid mesh is supported, so you can interpolate scatter points data to grid data and then do contour analysis. You can found the demo code package here: http://www.meteothinker.com/downloads/index.html .

**Comment by JustinCase1089** [comment]
Thanks a lot


Sent from my Spaceship
-------- Original message --------From: Yaqiang Wang <notifications@github.com> Date: 3/11/17  17:59  (GMT+10:00) To: meteoinfo/wContour_CSharp <wContour_CSharp@noreply.github.com> Cc: Franz Thomsen <post@franzthomsen.dk>, Author <author@noreply.github.com> Subject: Re: [meteoinfo/wContour_CSharp] Contouring for unstructured mesh (#2) 
Only grid mesh is supported, so you can interpolate scatter points data to grid data and then do contour analysis. You can found the demo code package here: http://www.meteothinker.com/downloads/index.html .

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/meteoinfo/wContour_CSharp","title":"meteoinfo/wContour_CSharp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/meteoinfo/wContour_CSharp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Yaqiang in #2: Only grid mesh is supported, so you can interpolate scatter points data to grid data and then do contour analysis. You can found the demo code package here: http://www.meteothinker.com/downloads/index.html ."}],"action":{"name":"View Issue","url":"https://github.com/meteoinfo/wContour_CSharp/issues/2#issuecomment-341640301"}}}
